const make = (slug, folder, name, description, category, visuals, tags) => ({
  id: `ShotCraft-${slug}`, slug, name, description, category,
  compatibleVisuals: visuals,
  tags: tags.map(([zh, en]) => ({zh, en})),
  preview: {poster: `media/poster/${slug}.png`, mp4: `media/${slug}.mp4`},
  source: {adapter: 'shotcraft-native', component: `templates/${folder}/${slug}.tsx`, schema: `templates/${folder}/schema.json`, sampleData: `templates/${folder}/sample-data.json`},
});
module.exports = [
  {...make('CharacterPerspectiveBoard', 'character-perspective-board',
    {zh: '角色主持与透视数据板', en: 'Character Presenter & Perspective Board'},
    {zh: '猫或自定义角色主持，搭配稳定的倾斜透视数据板，按设问、逐项证据、结论推进。附家庭账本与物流两组可替换示例。', en: 'A cat or custom presenter with a stable perspective data board: question, staged evidence, takeaway. Includes household and logistics datasets.'},
    'presenter_explainer', ['presenter', 'bar_chart', 'categorical_data'], [['角色主持', 'Character presenter'], ['透视数据板', 'Perspective board'], ['故事节拍', 'Story beats']]),
    preview: {poster: 'media/poster/CharacterPerspectiveBoard.png', mp4: 'media/CharacterPerspectiveBoard.mp4', durationSeconds: 14}},
  {...make('PortraitRankedReveal', 'portrait-ranked-reveal',
    {zh: '竖屏倒序榜单', en: 'Portrait Countdown Ranking'},
    {zh: '独立设计的 9:16 榜单故事：先设问，再逐项揭晓，最后保留领先结论。为手机留出右侧操作区与底部字幕区。', en: 'A purpose-built 9:16 ranking story: hook, staged countdown, and a retained takeaway, with space reserved for mobile controls and captions.'},
    'ranking_reveal', ['ranking', 'bar_chart', 'categorical_data'], [['竖屏 9:16', 'Portrait 9:16'], ['倒序揭晓', 'Countdown'], ['手机阅读', 'Mobile reading']]),
    preview: {poster: 'media/poster/PortraitRankedReveal.png', mp4: 'media/PortraitRankedReveal.mp4', width: 1080, height: 1920}},
  make('PresenterEvidenceBoard', 'presenter-evidence-board',
    {zh: '主持人逐项解读', en: 'Presenter Evidence Board'},
    {zh: '主持人图片区与数据板分区呈现，按讲解节拍逐项展示、强调和归纳。可替换主持人图片或视频。', en: 'A presenter image or video alongside a data board, with timed evidence reveals, emphasis, and a final takeaway.'},
    'presenter_explainer', ['presenter', 'bar_chart', 'categorical_data'], [['人物讲解', 'Presenter'], ['分步证据', 'Staged evidence'], ['同尺度', 'Shared scale']]),
  make('FootageEvidenceReveal', 'footage-evidence-reveal',
    {zh: '实景转入数据证据', en: 'Footage to Evidence'},
    {zh: '先观看连续实景视频，再引入稳定数据区，依次展示同尺度指标和结论。短素材末帧停留，不循环。', en: 'Establish continuous footage, then introduce a stable evidence area with shared-scale metrics and a takeaway. Short clips hold their final frame.'},
    'video_data_fusion', ['video', 'bar_chart', 'categorical_data', 'contextual_footage'], [['视频情境', 'Video context'], ['逐步揭示', 'Evidence reveal'], ['可编辑数据', 'Editable data']]),
  make('RankedReveal', 'ranked-reveal',
    {zh: '倒序揭晓排行榜', en: 'Countdown Ranking Reveal'},
    {zh: '从末位逐项揭晓排名，已出现的对象持续保留，数值与条长来自同一数据，最后强调领先差距。', en: 'Reveal a ranking from bottom to top, preserve settled rows, and close on the leading margin. Values and bars share one data source.'},
    'ranking_reveal', ['ranking', 'bar_chart', 'categorical_data'], [['倒序揭晓', 'Countdown'], ['榜单', 'Ranking'], ['节拍', 'Narrative beats']]),
];
