import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {EventEmitter} from 'node:events';
import {PassThrough} from 'node:stream';
import {createDesktopBridge,isLocalRequest,desktopCapability} from '../workbench/motion/server/desktop.mjs';
const request=(host='localhost:5190',peer='127.0.0.1',origin=`http://${host}`)=>({headers:{host,origin},socket:{remoteAddress:peer}});
test('desktop installation recognizes loopback only and refuses DNS rebinding',()=>{assert.ok(isLocalRequest(request()));assert.ok(isLocalRequest(request('[::1]:5190','::1')));for(const r of [request('evil.invalid:5190'),request('localhost:5190','10.0.0.2'),request('10.123.4.51:5190','127.0.0.1')])assert.equal(isLocalRequest(r),false);assert.equal(desktopCapability(request(),'linux').canInstall,false);assert.equal(desktopCapability(request(),'darwin').canInstall,true);});
test('Mac installation requires same-origin confirmation and the local capability token',()=>{const bridge=createDesktopBridge('/unused',{platform:'darwin'});const token=bridge.capability(request()).token;for(const [r,body] of [[request(),{token,confirm:false}],[request(),{token:'wrong',confirm:true}],[request('localhost:5190','127.0.0.1','https://evil.invalid'),{token,confirm:true}],[request('10.123.4.51:5190','10.0.0.2'),{token,confirm:true}]])assert.throws(()=>bridge.start(r,body));assert.equal(bridge.capability(request('10.123.4.51:5190','10.0.0.2')).token,undefined);});
test('server and incomplete packages cannot invoke local installation',()=>{let spawned=false;const bridge=createDesktopBridge('/unused',{platform:'linux',spawnProcess:()=>{spawned=true;}});assert.throws(()=>bridge.start(request(),{confirm:true,token:bridge.capability(request()).token}));assert.equal(spawned,false);const mac=createDesktopBridge('/unused',{platform:'darwin',spawnProcess:()=>{spawned=true;}});assert.throws(()=>mac.start(request(),{confirm:true,token:mac.capability(request()).token,exportId:'00000000-0000-0000-0000-000000000000'}),/先完成/);assert.equal(spawned,false);});
test('local bridge passes fixed bundle paths, tracks installer progress and preserves desktop validation boundary',()=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'datamagic-desktop-test-'));
  try{
    const id='00000000-0000-0000-0000-000000000000',folder=path.join(root,'out/motion',id);fs.mkdirSync(path.join(folder,'package'),{recursive:true});for(const [name,value] of [['READY.json',{}],['project.json',{name:'城市故事'}],['package/manifest.json',{}]])fs.writeFileSync(path.join(folder,name),JSON.stringify(value));
    let command;const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();
    const bridge=createDesktopBridge(root,{platform:'darwin',spawnProcess:(...args)=>{command=args;return child;}});const body={exportId:id,confirm:true,token:bridge.capability(request()).token};const job=bridge.start(request(),body);
    assert.equal(command[0],'python3');assert.ok(command[1].includes('--yes'));assert.ok(command[1].includes(path.join(folder,'package')));assert.throws(()=>bridge.start(request(),body),/正在运行/);
    child.stdout.write('{"type":"progress","message":"准备本机环境"}\n');assert.equal(bridge.status(request(),job.id).progress,'准备本机环境');child.stdout.write('{"status":"installed","draftName":"DataMagic-城市故事","appLaunched":true,"desktopValidated":false}\n');child.emit('exit',0);const result=bridge.status(request(),job.id);assert.equal(result.status,'installed');assert.equal(result.desktopValidated,false);assert.throws(()=>bridge.status(request('10.0.0.2','10.0.0.2'),job.id));
  }finally{fs.rmSync(root,{recursive:true,force:true});}
});
test('missing Python and failed installers are reported as failures, never installed',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'datamagic-desktop-error-'));try{const id='00000000-0000-0000-0000-000000000000',folder=path.join(root,'out/motion',id);fs.mkdirSync(path.join(folder,'package'),{recursive:true});for(const name of ['READY.json','package/manifest.json'])fs.writeFileSync(path.join(folder,name),'{}');fs.writeFileSync(path.join(folder,'project.json'),'{"name":"Test"}');const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();const bridge=createDesktopBridge(root,{platform:'darwin',spawnProcess:()=>child});const job=bridge.start(request(),{exportId:id,confirm:true,token:bridge.capability(request()).token});child.stderr.write('private-device-field-never-returned');child.emit('exit',1);const result=bridge.status(request(),job.id);assert.equal(result.status,'failed');assert.ok(!JSON.stringify(result).includes('private-device-field'));}finally{fs.rmSync(root,{recursive:true,force:true});}});
